# frozen_string_literal: true

source "https://rubygems.org"

gem "rake"
gem "thor", "~> 1.4"
gem "activesupport"
gem "activemodel"
gem "json", "~> 2.15.2"

# docs
gem "jekyll", "~> 4.3"
gem "jekyll-redirect-from", "~> 0.16"

group :development do
  gem "rubocop-shopify", require: false
  gem "debug", ">= 1.0.0", require: false
end

group :test do
  gem "minitest"
  gem "minitest-hooks"
  gem "mocha"
  gem "railties"
  gem "minitest-silence", require: false
end
