# frozen_string_literal: true

source "https://rubygems.org"

gem "thor", "~> 1.3"
gem "activesupport"
gem "sorbet-runtime"

group :development do
  gem "rubocop-shopify", require: false
  gem "sorbet"
  gem "tapioca"
end
