# frozen_string_literal: true

source "https://rubygems.org"

gem "thor", "~> 1.3"
gem "activesupport"
gem "activemodel"
gem "json", "~> 2.7.2"

group :development do
  gem "rubocop-shopify", require: false
end

group :test do
  gem "mocha"
end
