# frozen_string_literal: true

require "rake/testtask"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.pattern = "test/**/*_test.rb"
end

task default: :test

desc "Run benchmarks"
task :benchmark do
  ruby "test/benchmarks.rb"
end
