# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::DateAndTime::Calculations; end
module ::DateAndTime::Zones; end
module ActiveSupport::ArrayInquirer; end
module ActiveSupport::Multibyte::Chars; end
module ActiveSupport::SafeBuffer; end
module ActiveSupport::StringInquirer; end
module ActiveSupport::TimeZone; end
