name: Apply steps.json and open PR

on:
  workflow_dispatch:
  push:
    paths:
      - steps.json

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install dependencies
        env:
          BUNDLE_GEMFILE: dev/Gemfile
        run: |
          gem install bundler
          bundle config set path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Apply steps
        env:
          BUNDLE_GEMFILE: dev/Gemfile
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y jq

          total=$(jq '.steps | length' steps.json)
          echo "Found $total steps"

          i=0
          jq -c '.steps[]' steps.json | while read -r step; do
            i=$((i+1))
            op=$(jq -r '.op' <<<"$step")
            echo
            echo "[$i/$total] op=$op"

            case "$op" in
              add_attribute)
                name=$(jq -r '.name' <<<"$step")
                description=$(jq -r '.description' <<<"$step")
                base=$(jq -r '.base_attribute_friendly_id // empty' <<<"$step")
                values_csv=$(jq -r '(.values // []) | join(",")' <<<"$step")
                cmd=(bundle exec dev/bin/product_taxonomy add_attribute "$name" "$description")
                if [ -n "$base" ]; then
                  cmd+=("--base-attribute-friendly-id" "$base")
                fi
                if [ -n "$values_csv" ]; then
                  cmd+=("--values" "$values_csv")
                fi
                printf '==> %q ' "${cmd[@]}"; echo
                "${cmd[@]}" || true
                ;;
              add_category)
                name=$(jq -r '.name' <<<"$step")
                parent_id=$(jq -r '.parent_id' <<<"$step")
                id=$(jq -r '.id // empty' <<<"$step")
                cmd=(bundle exec dev/bin/product_taxonomy add_category "$name" "$parent_id")
                if [ -n "$id" ]; then
                  cmd+=("--id" "$id")
                fi
                printf '==> %q ' "${cmd[@]}"; echo
                "${cmd[@]}" || true
                ;;
              add_attributes_to_categories)
                attr_csv=$(jq -r '.attribute_friendly_ids | join(",")' <<<"$step")
                cat_csv=$(jq -r '.category_ids | join(",")' <<<"$step")
                include=$(jq -r '(.include_descendants // false) | tostring' <<<"$step")
                cmd=(bundle exec dev/bin/product_taxonomy add_attributes_to_categories "$attr_csv" "$cat_csv")
                if [ "$include" = "true" ]; then
                  cmd+=("--include-descendants")
                fi
                printf '==> %q ' "${cmd[@]}"; echo
                "${cmd[@]}" || true
                ;;
              add_value)
                name=$(jq -r '.name' <<<"$step")
                attribute_friendly_id=$(jq -r '.attribute_friendly_id' <<<"$step")
                cmd=(bundle exec dev/bin/product_taxonomy add_value "$name" "$attribute_friendly_id")
                printf '==> %q ' "${cmd[@]}"; echo
                "${cmd[@]}" || true
                ;;
              *)
                echo "Unknown op: $op — skipping"
                ;;
            esac
          done

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Apply steps from steps.json
          title: Apply steps from steps.json
          body: |
            This PR was automatically generated by the apply-steps workflow.
            It runs `scripts/apply_steps.rb` which consumes `steps.json` and invokes the taxonomy CLI to update data and docs.
          branch: automation/apply-steps
          delete-branch: true
          labels: automation, product-taxonomy


