name: Generate and commit distribution files to requested PR

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

concurrency:
  group: "dist"
  cancel-in-progress: false

jobs:
  generate_dist:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/generate_dist' }}
    steps:
    - uses: actions/checkout@v4
    - name: Checkout PR
      run: gh pr checkout $ISSUE
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # read-only token, exposed to `make`
        ISSUE: ${{ github.event.issue.html_url }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: cue-lang/setup-cue@v1.0.0
      with:
        version: 'v0.7.0'
    - name: Generate distribution files
      run: VERBOSE=1 make build
    - name: Upload distribution files
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist/
  commit_dist:
    runs-on: ubuntu-latest
    needs: generate_dist
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Checkout PR
      run: gh pr checkout $ISSUE
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # write token; only exposed to in-workflow commands
        ISSUE: ${{ github.event.issue.html_url }}
    - name: Download dist
      uses: actions/download-artifact@v4
      with:
        name: dist
    - name: Commit distribution files
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add dist
        git commit -m "🤖 Update distribution files" || exit 0 # Exit gracefully if no changes
        git push
